AWSTemplateFormatVersion: '2010-09-09'
Description: Data quality template, creates a nested stack for Glue Table and Crawler

Parameters:
  TemplateBucketBaseUrl:
    Type: String
    Description: The S3 bucket from which to fetch the templates used by this stack.
  GlueServiceRoleArn:
    Type: String
    Description: Service role for the Glue Crawler.
  LogsBucketName:
    Type: String
    Description: Logs bucket name
  GlueDatabaseName:
    Description: Name of the Glue Database
    Type: String
  MandatesTableName:
    Type: String
    Description: |
      DynamoDb table name for pn-mandate, valorized by the related output
      in the storage.yaml template, used also for identifying the S3 bucket
      directory where related CDC files are stored.
  
  MandatesGlueTableName:
    Type: String
    AllowedPattern: '^[a-z_]+$'
    ConstraintDescription: | 
       Glue table name for pn-mandate, accept only lowercase values and underscores.
    Default: pn_mandate

Resources:
  PnMandateDataQualityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/cdc-glue.yaml"
      Parameters:
        DynamoTableName: !Ref MandatesTableName
        GlueTableName: !Ref MandatesGlueTableName
        GlueServiceRoleArn: !Ref GlueServiceRoleArn
        LogsBucketName: !Ref LogsBucketName
        GlueDatabaseName: !Ref GlueDatabaseName
        DynamoDBKeysStructure: |
            struct<pk:struct<S:string>,sk:struct<S:string>>
        DynamoDBNewImageStructure: |
            struct<
              pk:struct<S:string>,
              sk:struct<S:string>,
              d_validto:struct<S:string,NULL:boolean>,
              s_delegatoruid:struct<S:string,NULL:boolean>,
              s_validationcode:struct<S:string,NULL:boolean>,
              i_state:struct<N:string,NULL:boolean>,
              b_delegateisperson:struct<BOOL:boolean,NULL:boolean>,
              d_validfrom:struct<S:string,NULL:boolean>,
              s_delegate:struct<S:string,NULL:boolean>,
              s_mandateid:struct<S:string,NULL:boolean>,
              t_created:struct<S:string,NULL:boolean>,
              b_delegatorisperson:struct<BOOL:boolean,NULL:boolean>,
              i_ttl:struct<N:string,NULL:boolean>,
              s_delegatortype:struct<S:string,NULL:boolean>,
              mandateId:struct<S:string,NULL:boolean>
            >