package it.pagopa.pn.ciechecker.model;

import it.pagopa.pn.ciechecker.CieCheckerConstants;

@lombok.CustomLog
public enum ResultCieChecker {
    OK("OK"),
    KO("KO"),
    KO_EXC_INPUT_PARAMETER_NULL( CieCheckerConstants.EXC_INPUT_PARAMETER_NULL),
    KO_EXC_INVALID_PARAMETER_CIESOD(CieCheckerConstants.EXC_INVALID_PARAMETER_CIESOD) ,
    KO_EXC_INVALID_PARAMETER_MRTDSOD(CieCheckerConstants.EXC_INVALID_PARAMETER_MRTDSOD),
    KO_EXC_INVALID_PARAMETER_CIENIS(CieCheckerConstants.EXC_INVALID_PARAMETER_CIENIS),
    KO_EXC_INVALID_PARAMETER_PUBLICKEY(CieCheckerConstants.EXC_INVALID_PARAMETER_PUBLICKEY),
    KO_EXC_INVALID_PARAMETER_SIGNEDNONCE(CieCheckerConstants.EXC_INVALID_PARAMETER_SIGNEDNONCE),
    KO_EXC_INVALID_PARAMETER_NONCE(CieCheckerConstants.EXC_INVALID_PARAMETER_NONCE),
    KO_EXC_INVALID_PARAMETER_MRTDDG1(CieCheckerConstants.EXC_INVALID_PARAMETER_MRTDDG1),
    KO_EXC_INVALID_PARAMETER_MRTDDG11(CieCheckerConstants.EXC_INVALID_PARAMETER_MRTDDG11),
    KO_EXC_NOTFOUND_CERTIFICATES(CieCheckerConstants.EXC_NOTFOUND_CERTIFICATES),
    KO_EXC_NOTFOUND_CMSSIGNEDDATA(CieCheckerConstants.EXC_NOTFOUND_CMSSIGNEDDATA),
    KO_EXC_CERTIFICATE_NOT_SIGNED (CieCheckerConstants.EXC_CERTIFICATE_NOT_SIGNED),
    KO_EXC_NO_CSCA_ANCHORS_PROVIDED ( CieCheckerConstants.EXC_NO_CSCA_ANCHORS_PROVIDED),
    KO_EXC_PARSED_ZERO_CSCA_CERTIFICATES (CieCheckerConstants.EXC_PARSED_ZERO_CSCA_CERTIFICATES),
    KO_EXC_NO_SIGNERINFORMATION(CieCheckerConstants.EXC_NO_SIGNERINFORMATION),
    KO_EXC_PARSING_CERTIFICATION(CieCheckerConstants.EXC_PARSING_CERTIFICATION),
    KO_EXC_GENERATE_CERTIFICATE(CieCheckerConstants.EXC_GENERATE_CERTIFICATE),
    KO_EXC_GENERATE_CMSSIGNEDDATA(CieCheckerConstants.EXC_GENERATE_CMSSIGNEDDATA),
    KO_EXC_VALIDATE_CERTIFICATE(CieCheckerConstants.EXC_VALIDATE_CERTIFICATE),
    KO_EXC_NO_SUPPORTED_CERTIFICATEPATHVALIDATOR(CieCheckerConstants.EXC_NO_SUPPORTED_CERTIFICATEPATHVALIDATOR),
    KO_EXC_INVALID_PARAMETER_CERTPATHVALIDATOR(CieCheckerConstants.EXC_INVALID_PARAMETER_CERTPATHVALIDATOR),
    KO_EXC_IOEXCEPTION(CieCheckerConstants.EXC_IOEXCEPTION),
    KO_EXC_NO_HASH_ALGORITHM_SOD(CieCheckerConstants.EXC_NO_HASH_ALGORITHM_SOD),
    KO_EXC_NO_HASH_SIGNED_DATA(CieCheckerConstants.EXC_NO_HASH_SIGNED_DATA),
    KO_EXC_UNSUPPORTED_ALGORITHM_SOD(CieCheckerConstants.EXC_UNSUPPORTED_HASH_ALGORITHM_SOD),
    KO_EXC_NOTFOUND_EXPECTED_HASHES_SOD(CieCheckerConstants.EXC_NO_EXPECTED_HASHES_FOUND_SOD),
    KO_EXC_NOTFOUND_DIGEST_SOD(CieCheckerConstants.EXC_NOTFOUND_DIGEST),
    KO_EXC_NOTFOUND_MRTD_SOD(CieCheckerConstants.EXC_NOTFOUND_MRTD_SOD),
    KO_EXC_NO_MATCH_NONCE_SIGNATURE(CieCheckerConstants.EXC_NO_MATCH_NONCE_SIGNATURE),
    KO_EXC_GENERATE_PUBLICKEY(CieCheckerConstants.EXC_GENERATE_PUBLICKEY),
    KO_EXC_EXTRACTION_PUBLICKEY(CieCheckerConstants.EXC_EXTRACTION_PUBLICKEY),
    KO_EXC_PARSING_HEX_BYTE(CieCheckerConstants.EXC_PARSING_HEX_BYTE),
    KO_EXC_INVALID_CRYPTOGRAPHIC_OPERATION(CieCheckerConstants.EXC_INVALID_CRYPTOGRAPHIC_OPERATION),
    KO_EXC_NO_SIGNATURES_SIGNED_DATA(CieCheckerConstants.EXC_NO_SIGNATURES_SIGNED_DATA),
    KO_EXC_NO_SIGNERINFORMATIONSTORE(CieCheckerConstants.EXC_NO_SIGNERINFORMATIONSTORE),
    KO_EXC_NO_MESSAGEDIGESTSPI_SUPPORTED(CieCheckerConstants.EXC_NO_MESSAGEDIGESTSPI_SUPPORTED),
    KO_EXC_NO_HASH_CONTENT_MATCH(CieCheckerConstants.EXC_NO_HASH_CONTENT_MATCH),
    KO_EXC_NO_SIGNED_ATTRIBUTE(CieCheckerConstants.EXC_NO_SIGNED_ATTRIBUTE),
    KO_EXC_NO_MATCH_NIS_HASHES_DATAGROUP(CieCheckerConstants.EXC_NO_MATCH_NIS_HASHES_DATAGROUP),
    KO_EXC_INVALID_CMSTYPEDDATA(CieCheckerConstants.EXC_INVALID_CMSTYPEDDATA),
    KO_EXC_NO_NIS_HASHES_DATAGROUP(CieCheckerConstants.EXC_NO_NIS_HASHES_DATAGROUP),
    KO_EXC_ERROR_CREATE_VERIFIER(CieCheckerConstants.EXC_ERROR_CREATE_VERIFIER),
    KO_EXC_NOVALID_DIGITAL_SIGNATURE(CieCheckerConstants.EXC_NOVALID_DIGITAL_SIGNATURE),
    KO_EXC_NO_CMSTYPEDDATA(CieCheckerConstants.EXC_NO_CMSTYPEDDATA),
    KO_EXC_NOT_AVAILABLE_CRYPTOGRAPHIC_ALGORITHM(CieCheckerConstants.EXC_NOT_AVAILABLE_CRYPTOGRAPHIC_ALGORITHM),
    KO_EXC_NOT_AVAILABLE_SECURITY_PROVIDER(CieCheckerConstants.EXC_NOT_AVAILABLE_SECURITY_PROVIDER),
    KO_EXC_INVALID_KEY_SPECIFICATION(CieCheckerConstants.EXC_INVALID_KEY_SPECIFICATION),
    KO_EXC_NOFOUND_DIGITAL_SIGNATURE(CieCheckerConstants.EXC_NOFOUND_DIGITAL_SIGNATURE),
    KO_EXC_NOFOUND_SIGNER(CieCheckerConstants.EXC_NOFOUND_SIGNER),
    KO_EXC_NOT_SAME_DIGEST(CieCheckerConstants.EXC_NOT_SAME_DIGEST),
    KO_EXC_NO_SUPPORTED_CERTIFICATEFACTORY(CieCheckerConstants.EXC_NO_SUPPORTED_CERTIFICATEFACTORY),
    KO_EXC_DIGEST_NOT_VERIFIED(CieCheckerConstants.EXC_DIGEST_NOT_VERIFIED),
    KO_EXC_INVALID_VERIFIER(CieCheckerConstants.EXC_INVALID_VERIFIER),
    KO_EXC_EXCEPTION(CieCheckerConstants.EXC_KO);

    private final String value;
    public String getValue() {
        return value;
    }

    ResultCieChecker(String value) {
        this.value = value;
    }

    public static ResultCieChecker fromValue(String value) {
        for (ResultCieChecker b : ResultCieChecker.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        return ResultCieChecker.KO;
    }
}
