openapi: 3.0.1
info:
  title: PN Mandate u-service
  description: Documentation APIs v1.0
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /mandate-private/api/v1/mandates-by-internaldelegate/{internaluserId}:
    get:
      tags:
        - mandate-private-service
      description: Return only active mandates for delegate
      operationId: listMandatesByDelegate
      parameters:
        - name: internaluserId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InternalMandateDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate-private/api/v1/mandates-by-internaldelegator/{internaluserId}:
    get:
      tags:
        - mandate-private-service
      description: Return only active mandates for delegator
      operationId: listMandatesByDelegator
      parameters:
        - name: internaluserId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InternalMandateDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate/api/v1/count-by-delegate:
    get:
      tags:
        - mandate-service
      description: Return total mandates based on required status if filter's specified. If no filter is present, returns total of all pending and active mandates
      operationId: countMandatesByDelegate
      parameters:
        - name: status
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MandateCountsDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate/api/v1/mandate:
    post:
      tags:
        - mandate-service
      description: Create a new mandate, returns the just created mandate if successful
      operationId: createMandate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MandateDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MandateDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate/api/v1/mandate/{mandateId}/accept:
    patch:
      tags:
        - mandate-service
      description: Accept a mandate
      operationId: acceptMandate
      parameters:
        - name: mandateId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptRequestDto'
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate/api/v1/mandate/{mandateId}/reject:
    patch:
      tags:
        - mandate-service
      description: Reject a mandate
      operationId: rejectMandate
      parameters:
        - name: mandateId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate/api/v1/mandate/{mandateId}/revoke:
    patch:
      tags:
        - mandate-service
      description: Revoke a mandate
      operationId: revokeMandate
      parameters:
        - name: mandateId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate/api/v1/mandates-by-delegate:
    get:
      tags:
        - mandate-service
      description: Return filtered mandates based on required status if filter's specified. If no filter is present, returns all pending and active mandates
      operationId: listMandatesByDelegate_1
      parameters:
        - name: status
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MandateDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
  /mandate/api/v1/mandates-by-delegator:
    get:
      tags:
        - mandate-service
      description: Return all pending and active mandates
      operationId: listMandatesByDelegator_1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MandateDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
components:
  schemas:
    InternalMandateDto:
      type: object
      properties:
        mandateId:
          type: string
        delegator:
          type: string
        delegate:
          type: string
        visibilityIds:
          type: array
          items:
            type: string
        datefrom:
          type: string
          description: ISO 8601 format
        dateto:
          type: string
          description: ISO 8601 format
    Fault:
      type: object
      properties:
        type:
          type: string
          description: URI reference of type definition
        status:
          maximum: 600
          minimum: 100
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          format: int32
        title:
          type: string
          description: A short, summary of the problem type. Written in english and readable
        detail:
          type: string
          description: A human readable explanation of the problem.
    MandateCountsDto:
      type: object
      properties:
        value:
          type: integer
          format: int32
    MandateDto:
      type: object
      properties:
        mandateId:
          type: string
          description: Available always, not required on mandate creation.
          nullable: true
        delegator:
          $ref: '#/components/schemas/UserDto'
        delegate:
          $ref: '#/components/schemas/UserDto'
        status:
          type: string
          description: Available always, not required on mandate creation.
          nullable: true
          enum:
            - pending
            - active
            - revoked
            - rejected
            - expired
        visibilityIds:
          type: array
          description: Available always, not required on mandate creation.
          nullable: true
          items:
            $ref: '#/components/schemas/OrganizationIdDto'
        verificationCode:
          type: string
          description: Available only for request where requesting user is the delegator
          nullable: true
        datefrom:
          type: string
          description: ISO 8601 format
        dateto:
          type: string
          description: ISO 8601 format
    OrganizationIdDto:
      type: object
      properties:
        name:
          type: string
        uniqueIdentifier:
          type: string
      description: Available always, not required on mandate creation.
      nullable: true
    UserDto:
      type: object
      properties:
        displayName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        companyName:
          type: string
        fiscalCode:
          type: string
        email:
          type: string
        person:
          type: boolean
      description: Available only for request where requesting user is the delegator
      nullable: true
    AcceptRequestDto:
      type: object
      properties:
        verificationCode:
          type: string
    ServerResponse:
      type: object
